services:
  - type: web
    name: goruntulu-konusma
    env: node
    plan: free
    buildCommand: npm install
    startCommand: NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production 